import type { SimpleRouteJson } from "@tscircuit/capacity-autorouter"
import { GenericSolverDebugger } from "@tscircuit/solver-utils/react"
import { FanoutSolver } from "lib/fanout-solver"
import type { FanoutSolverOptions } from "lib/types"
import capturedFixture from "../tests/fixtures/am62l-lpddr4-ram-above-soc-fanout.json"

type CapturedInput = SimpleRouteJson & {
  allowBlindAndBuriedVias?: boolean
  allowViaInPad?: boolean
}

const fixture = capturedFixture as unknown as {
  generatedFrom: {
    generator: "scripts/generate-repro/generate-repro04.tsx"
    layout: "ram_above"
  }
  inputSrj: CapturedInput
  options: FanoutSolverOptions
}

const busDescriptions = [
  "BYTE0 · top/left · 8 signals",
  "BYTE1 · top/right · 8 signals",
  "ADDR/CTRL · top/center · 8 signals",
  "CLOCK + DQS0 · top/left · 4 signals",
  "DQS1 · top/right · 2 signals",
  "RESET · top/center · 1 signal",
  "DMI0 · top/left · 1 signal",
  "DMI1 · top/right · 1 signal",
]

export const am62lTopEdgeBreakoutProvenance = fixture.generatedFrom

export const createAm62lTopEdgeBreakoutRepro = () => ({
  inputSrj: structuredClone(fixture.inputSrj),
  options: structuredClone(fixture.options),
})

export default function Am62lTopEdgeBreakoutReproPage() {
  return (
    <div
      style={{
        minHeight: "100vh",
        background: "#f8fafc",
        color: "#0f172a",
        fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif",
      }}
    >
      <header
        style={{
          borderBottom: "1px solid #e2e8f0",
          background: "#ffffff",
          display: "grid",
          gap: 10,
          padding: 16,
        }}
      >
        <div>
          <strong>Repro 04 · AM62L nine-bus top-edge breakout</strong>
          <div style={{ color: "#475569", fontSize: 13, marginTop: 4 }}>
            SoC fanout phase · 135 connections · 589 phase obstacles · 8 layers
          </div>
        </div>

        <div style={{ color: "#475569", fontSize: 13 }}>
          Generated by scripts/generate-repro/generate-repro04.tsx with
          @tscircuit/core and renderUntilSettled, then captured through the
          SOC_FANOUT algorithmFn. This repro does not rotate or redistribute any
          points.
        </div>

        <div
          style={{
            display: "flex",
            flexWrap: "wrap",
            gap: 8,
          }}
        >
          {busDescriptions.map((description) => (
            <span
              key={description}
              style={{
                background: "#eef2ff",
                border: "1px solid #c7d2fe",
                borderRadius: 999,
                color: "#3730a3",
                fontSize: 12,
                padding: "5px 9px",
              }}
            >
              {description}
            </span>
          ))}
        </div>

        <div style={{ color: "#b45309", fontSize: 13 }}>
          The colored rings inside the BGA are source pads. Core placed all 33
          downstream breakout points on the top boundary.
        </div>

        <div style={{ color: "#b45309", fontSize: 13 }}>
          Routes all 135 connections, including 102 plane drops, with the
          original bus and differential-pair length constraints. Use the
          debugger controls to inspect the routing and length tuning.
        </div>
      </header>

      <GenericSolverDebugger
        createSolver={() => {
          const { inputSrj, options } = createAm62lTopEdgeBreakoutRepro()
          return new FanoutSolver(inputSrj, options)
        }}
        animationSpeed={80}
      />
    </div>
  )
}
